[build]
  command = "pnpm build"
  publish = "build/"

[build.environment]
  NPM_FLAGS="--prefix=/dev/null"
  NODE_VERSION = "14"

[context.production]
  command = "pnpm netlify:build:production"

[context.deploy-preview]
  command = "pnpm netlify:build:deployPreview"

[context.branch-deploy]
  command = "pnpm netlify:build:deployPreview"

[[plugins]]
package = "../.netlify/netlify-plugin-pnpm"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
